# -*- coding: utf-8 -*-
"""Aulas - Faculdadeipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9vy5eD0gyirhWjE_Vn9ow-e2ze92qiU

# Aula 4
"""

#Informações da Compra.

preco_unitario = float(input('Preço Unitário? R$ '))
quantidade = int(input('Quantidade: '))
desconto = float(input('Qual o Desconto: %'))

#Escolhe a Forma de Pagamento.

print('Escolha a forma de pagamento abaixo.')
print('1 - PIX')
print('2 - Dinheiro')
print('3 - Carteira Digital')
print('4 - Débito ou Crédito')
#Escolhe a Forma de Pagamento
pagamento = int(input('>> '))

#Cálculo para o preço total

preco_total = quantidade * preco_unitario

#Se a quantidade for múltiplo de 4, aplica-se o desconto na compra.

if ((quantidade % 4) == 0) and (pagamento == 1 or pagamento == 2):
  
  #Aplica-se o desconto no preço final.
  preco_total = preco_total * (1-(desconto/100))
  print('Desconto de {:.2f}%'.format(desconto))
else:
  #Sem Desconto
  print('Desconto não aplicado')

#Exibe o preço final.
print('Preço Final: R$ {:.2f}'.format(preco_total))

"""# Aula 5"""

#Formatação

valor_string = 'Exemplo'
f'{valor_string:<15}'
f'{valor_string:>15}'
f'{valor_string:^15}'

sabor = 'Chocolate:'
total = 19.9

print(f'{sabor:<20} R$ {total:.2f}')

#Linhas de donut com preço unitário

print('Escolha a quantidade de donuts e a linha que deseja.')
quantidade_classica = int(input('Quantidade de Donuts da linha clássica: '))
quantidade_premium  = int(input('Quantidade de Donuts da linha premium: '))
quantidade_recheado = int(input('Quantidade de Donuts da linha recheado: '))
quantidade_total = quantidade_classica + quantidade_premium + quantidade_recheado

#Forma de Pagamento

print('Escolha a forma de pagamento abaixo.')
print('1 - PIX')
print('2 - Dinheiro')
print('3 - Débito ou Crédito')

pagamento = int(input('>> '))

#Preços dos Donuts

preco_classica = 9.9
preco_premium = 11.9
preco_recheado = 13.9

preco_total = (quantidade_classica * preco_classica) + (quantidade_premium * preco_premium) + (quantidade_recheado * preco_recheado)

#Se for múltiplo de 4 aplicar desconto de 2 reais no total da compra

if ((quantidade_total % 4) == 0) and (pagamento == 1 or pagamento == 2):

 #aplica-se desconto de 2 reais
 preco_total = preco_total - 2
 print('Desconto de R$ 2,00 aplicado')
else:
  print('Desconto não aplicado')
print(f'Total da compra: {preco_total:.2f}')

"""# Aula 6"""

def maior(num1, num2):
  if (num1 > num2) or (num1 == num2):
    return num1
  else:
    return num2
  
print(maior(6, 9))
print(maior(5, 0))
print(maior(3, 2))
print(maior(1, 1))

def subtracao(n1, n2):
  global s
  s = n1-n2
  return s

subtracao(2, 1)
print(s)

def getTipoDonut():
  global tipo_donut
  tipo_donut = input('Qual o tipo de donut? ')

def getQtdDonut():
  global qtd_donut
  qtd_donut = int(input(f'Quantos {tipo_donut}? '))

def getCaixaDonut():
  global qtd_caixa, tipo_caixa
  
  if qtd_donut %5 == 0:
    tipo_caixa = "fechada"
  else:
    tipo_caixa = "sobrando espaço"
  
  qtd_caixa = int(round(qtd_donut/5, 0))
  

getTipoDonut()
getQtdDonut()
getCaixaDonut()

print(f'{qtd_caixa} caixa(s) {tipo_caixa}')

"""# Aula 7 """

n = int(input())
i = 0

while i < 5:
  if n %2 == 0:
    n += 2
    print(n)
  else:
    n += 1
    print(n)
  i += 1
print('Os valores constam acima')

#Recebe o número do usuário
num = int(input('\nInsira um número: '))

i = 0 #Contador
while i < 5:
  #Se par
  if (num % 2 == 0):
    num += 2
  #Se ímpar
  else:
    num += 1
  
  print(num)
  #Incrementa o contador
  i += 1

print('\nOs valores constam acima')

"""# AC 1"""

#Primeira

tempo_1 = int(input('Tempo 1: '))
tempo_2 = int(input('Tempo 2: '))
tempo_3 = int(input('Tempo 3: '))

tempo_total = tempo_1 + tempo_2 + tempo_3

print(f'{tempo_total} minutos')

#Segunda

preco_unit = float(input())
quantidade = int(input())

preco_total = quantidade * preco_unit
desconto =  (10 + quantidade)/100

print(f'{preco_total:.2f}')
print(f'{(preco_total-(preco_total*desconto)):.2f}')

#Terceira
polegada = float(input())

cm = polegada * 2.54

print(f'{cm:.3f} centímetros')

#Quarta
numero = int(input())
if numero >= 2:
  if numero %2 == 0:
    impar = numero - 1
    par = numero + 2
  else:
    impar = numero - 2
    par = numero - 1
  print(f'{impar} {par}')

#Quinta

nota_trabalhos = float(input())
nota_prova = float(input())
media_final = (nota_trabalhos + nota_prova)/2

if (media_final >= 6):
    print('aprovado')
elif (nota_trabalhos >= 2):
    print('talvez com a sub')
else:
    print('reprovado')

#Sexta

diasSemana = ["sabado", "domingo", "segunda", "terca", "quarta", "quinta", "sexta"]
indexDia = 0;
diaSemana = input();
prazo = int(input());
for x in diasSemana:
  if x == diaSemana:
    indexDia = diasSemana.index(x);
for x in range(prazo):
  indexDia+=1
  if indexDia > 6:
    indexDia = 0;
if prazo == 0:
  print("chega hoje!");
else:
  print("sera entregue",
diasSemana[indexDia]);

"""# Exercício while - Tipo Donut"""

import random, os, time

jogadas = ['pedra', 'papel', 'tesoura']
jogar = 1
while jogar:
    os.system('cls')

    print('\tPedra, Papel ou Tesoura\n\tFaça sua jogada!')
    user = str(input('\n\tVocê: ')).replace(' ', '').lower()

    while not(user in jogadas):
        print('\n\tFaça uma jogada válida!')
        user = str(input('\n\tVocê: ')).replace(' ', '').lower()

    else:
        bot = random.choice(jogadas)
        print(f'\tBot: {bot}')    

        if (user == bot):
            print('\n\tEmpate!')

        elif ((user == 'pedra' and bot == 'tesoura') 
        or (user == 'tesoura' and bot == 'papel') 
        or (user == 'papel' and bot == 'pedra')):
            print('\n\tVocê ganhou!')

        else:
            print('\n\tBot ganhou!')

    time.sleep(2)
    os.system('cls')

    print('\n\tO que deseja fazer agora?')
    print('\n\t[1] Jogar Novamente')
    print('\t[0] Sair')
    
    jogar = int(input('\n\t-> '))

#Lista com os tipos válidos
tipos = ['classico', 'premium', 'recheado']

comprar = 1
while comprar:
  print('\nTipos de Donuts: Classico, Premium e Recheado')
  #Recebe o tipo de donut
  tipo = str(input('Insira o tipo de donut: ')).lower()

  i = 1 #Contador de erros
  #Enquanto tipo for inválido e tentativa menor que 5
  while not(tipo in tipos) and (i < 5):
    print('\n\nInsira um tipo válido!')
    #Recebe o tipo de donut
    tipo = str(input('\nInsira o tipo de donut: ')).lower()
    #Incrementa o contador
    i += 1

  print('\nO que deseja fazer agora?')
  print('\n[1] Continuar comprando')
  print('[0] Sair')
  #Recebe se a compra vai continuar ou não
  comprar = int(input('\n-> '))

"""# AC 2 """

# 1 - Tabuada

num = int(input())

for count in range(10):
    print("%d x %d = %d" % (num, count+1, num*(count+1)) )

# 1 - Tabuada

num1 = int(input())
num2 = int(input())

if num1 > num2:
  print('Nenhuma tabuada no intervalo!')
else:
  for count in range(10):
    print("%d x %d = %d" % (num1, count+1, num1*(count+1)) )

#2 - Triângulo Alfabético

vezes = int(input("Vezes: "))


alfabeto = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']


for i in range(vezes):
    print(alfabeto[i]*(i+1))

# 3 - Doação

lista_vc = []

while True:
  vc = float(input())
  if vc == -1:
    break
  else:
    lista_vc.append(vc)

soma_vc = sum(lista_vc)
print(f'VC$ {soma_vc:.2f}')
print(f'R$ {(soma_vc * 2.50):.2f}')

# 4 - Pague o Aluguel

divida = int(input())
pagamento = int(input())

num_pagamento = 1
while divida > 0:
    print(f'pagamento: {num_pagamento}')
    print(f'antes = {divida}')

    divida -= pagamento
    if divida < 0:
        divida = 0
        
    print(f'depois = {divida}')
    print('-'*5)
    
    num_pagamento += 1



# 5 - Anos Bissextos

inicio = int(input())
fim = int(input())

cont = 0

for ano in range(inicio, fim + 1):
    if ano % 4 == 0 and ano % 100 != 0 or ano % 400 == 0:
        print(ano)
        cont += 1
      
print(f'bissextos: {cont}')

# 6 - intervalo de Primos

inicio = int(input())
fim = int(input())
contagem = 0
  
for i in range(inicio, fim+1): 
  if i>1: 
    for j in range(2,i): 
        if(i % j==0): 
            break
    else:
        contagem +=1
        print(i)
print(f'primos: {contagem}')

"""AC3
# Nova seção
"""

#Carrinho de Compras

cp = []
l = 0
def userInput():
    ui = input()
    ui = ui.split(" ")
    return ui

ui = userInput()

if ui:
    cp = ui

while l >= 0:
    ui = userInput()

    if ui[0] == "adicionar":
        s = f"{ui[1]}"
        cp.append(s)
    
    if ui[0] == "remover":
        try:
            cp.remove(ui[1])
        except:
            s = f"código {ui[1]} não encontrado"
            print(s)

    if ui[0] == "exibir":
        cp.sort(key = int)
        print(*cp)

    if ui[0] == "encerrar":
        cp.sort(key = int)
        print(*cp)
        break

    l+=1

#Exibir Tabuadas

1,t2 = input(), input()
t1,t2 = int(t1), int(t2)

def t(i):
    i = int(i)
    for c in range(10):
        c += 1
        s = f"{i} x {c} = {c*i}"
        print(s)
    print('-'*10)

if t1 > t2:
    print("Nenhuma tabuada no intervalo!")

for num in range(t1, t2+1):
    t(num)
© 2022 GitHub, Inc.
Terms
Privacy
Security

#ImpactaTube

counter, cns, cnsOut = input(), [], []
counter = int(counter)

for i in range(0,counter):
    temp = input()
    temp = temp.split(";")
    temp[1] = int(temp[1])
    temp[2] = float(temp[2])
    cns.append(temp)

X,Y = input(), input()
X,Y = float(X),float(Y)

for cn in cns:
    subs, cpm, prem = cn[1], cn[2], cn[3]
    subs = subs // 1000
    count = cpm + (subs * X if prem == "sim" else subs * Y)
    temp = f"{cn[0]}: R$ {count :.2f}"
    cnsOut.append(temp)

listCns = '\n'.join(s for s in cnsOut)
stirng = '''-----
BÔNUS
-----\n'''
print(stirng, end="")
print(listCns)

#Corra Forest!

times = []

while True:
    userInput = input()
    userInput = int( userInput )
    if ( userInput < 0 ):
        break
    times.append( userInput )

md = sum( times ) / len( times )
print( f"MEDIA: {md :.2f}" )

for time in times:
    if time < md:
        print(time)

#Segunda Chance

nts, out, alns, cng = [], [], input(), 0
alns = int(alns)

for i in range(0,alns):
    temp = input()
    temp = float(temp)
    nts.append(temp)

for i in range(0, alns):
    temp = input()
    temp = float(temp)
    nt = nts[i]

    if nt < 10 and temp == 10:
        cng+=1
        nt += 2 if nt < 9 and temp == 10 else 1

    out.append(nt)

print(f"NOTAS ALTERADAS: {cng}")

for index, o in enumerate(out):
    original, final = nts[index], o
    string = f"{'*' if final != original else '-'}({index + 1:0>3}) original: {original:0^5} | final: {final:0^5}"
    print(string)