# -*- coding: utf-8 -*-
"""Técnicas de Programação - Busca Linear e Binária

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15YLzfYogwa78bgD-8Mga7N2dxj-QJia4
"""

#Busca Linear

lista = [0, 1 , 2, 7, 15, 23, 56, 57, 58, 70, 72, 78]

def busca_linear(lista, item):
    for i in range(len(lista)):
        if lista[i] == item:
            return i
    return -1

busca_linear(lista, 70)

#Busca Linear

lista = [1 , 2, 7, 15, 23, 56, 57, 58, 70, 72, 78]

def busca_linear(lista, item):
    cont = 0
    for i in range(len(lista)):
        cont += 1
        if lista[i] == item:
            return cont
    return cont

busca_linear(lista, 30)

#Busca Binária

lista = [1 , 2, 7, 15, 23, 56, 57, 58, 70, 72, 78]

def busca_binaria(lista, item):
    cont = 0
    inicio = 0
    fim = len(lista) - 1
    while inicio <= fim:
        meio = (inicio + fim) // 2
        cont += 1
        if lista[meio] == item:
            return cont
        elif item > lista[meio]:
            inicio = meio + 1
        else:
            fim = meio - 1
    return cont

busca_binaria(lista, 15)

#Busca Binária AC 2

lista = sorted([2, 2, 0, 0, 7, 8, 5] * 2)

def busca_binaria(lista, item):
    cont = 0
    inicio = 0
    fim = len(lista) - 1
    while inicio <= fim:
        meio = (inicio + fim) // 2
        cont += 1
        if lista[meio] == item:
            return cont
        elif item > lista[meio]:
            inicio = meio + 1
        else:
            fim = meio - 1
    return cont

print(lista)
busca_binaria(lista, 8)

#Busca Binária AC 2

lista = sorted(["Alberta", "Bruna", "Alexa", "Claudia", "Priscila", "Lucy", "Darcy", "Silvia", "Marcia", "Anita", "Bruna"])

def busca_binaria(lista, item):
    cont = 0
    inicio = 0
    fim = len(lista) - 1
    while inicio <= fim:
        meio = (inicio + fim) // 2
        cont += 1
        if lista[meio] == item:
            return cont
        elif item > lista[meio]:
            inicio = meio + 1
        else:
            fim = meio - 1
    return cont

busca_binaria(lista, 'Bruna')